### ISSUE TITLE
panic: Meta: does not exist

### ISSUE THREAD

**Issue by mholttech** [andrewkroh/terraform-module-fleet#1]
I'm receiving the error "Panic: Meta: does not exist" when trying to run this against https://github.com/elastic/integrations/tree/main/packages/aws/data_stream/inspector

It looks like this function is supposed to account for variable shadowing but it doesn't seem to be working.
https://github.com/andrewkroh/terraform-module-fleet/blob/806cdebe59b2d569ee43207f7ebd4f5c4cbe9d87/fleet-terraform-generator/internal/module/generate.go#L256-L270

**Comment by andrewkroh** [comment]
Fixed in 06bca9b.

I did some refactoring last week to reduce duplication across some of my side-projects like this one, and it as a result missed updating "Meta" to "FileMetadata".

But once you have that fix, you will be hitting an error about this https://github.com/elastic/integrations/issues/6148. You can comment out that whole [block](
https://github.com/andrewkroh/terraform-module-fleet/blob/06bca9beb3210b91288209ad70fa3df56b762d72/fleet-terraform-generator/internal/module/generate.go#L257-L268) as a workaround, and I don't think you will have any problems (especially if you are not using the proxy_url setting).

**Comment by mholttech** [comment]
Awesome thanks! I stumbled upon your repo this morning from https://github.com/elastic/terraform-provider-elasticstack/issues/89#issuecomment-1571913779 and it looks like combining what was released in 0.6.0 with the work you've done is going to give us a path to move forward. We've been impacted by https://github.com/elastic/kibana/issues/157778#event-9468729230 since we upgraded to 8.7 over a month ago and since the fix won't be released until 8.8.2 ships they told us to try and use the APIs instead.

**Comment by andrewkroh** [comment]
I have been meaning to update the modules in this repo to take advantage of elasticstack 0.6.0, but haven't got around to it yet. That will fix this [bug](https://github.com/andrewkroh/terraform-module-fleet/blob/119097ed4997a2aebc52fac85b6b056d2fecb1c2/fleet_agent_policy/main.tf#L5-L7).

If there are more Fleet integrations you want added to the list in https://github.com/andrewkroh/terraform-module-fleet/blob/119097ed4997a2aebc52fac85b6b056d2fecb1c2/Makefile#L10-L15 then let me know or open a PR.
